name: Build Iceberg Spark Images

on:
  push:
    branches: [ main ]

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load matrix JSON
        id: set-matrix
        run: |
          MATRIX_JSON=$(jq -c . VERSIONS.json)
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  build:
    needs: load-matrix
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged

    strategy:
      matrix:
        include: ${{ fromJSON(needs.load-matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "Building image for catalog: ${{ matrix.catalog }}, version: ${{ matrix.catalog_version }}, spark: ${{ matrix.spark_version }}, scala: ${{ matrix.scala_version }}, java: ${{ matrix.java_version }}"

          docker build ./${{ matrix.catalog }} \
          --build-arg CATALOG_VERSION=${{ matrix.catalog_version }} \
          --build-arg JAVA_VERSION=${{ matrix.java_version }} \
          --build-arg SCALA_VERSION=${{ matrix.scala_version }} \
          --build-arg SPARK_VERSION=${{ matrix.spark_version }} \
          -t ${{ github.repository_owner }}/spark-connect:${{ matrix.catalog }}${{ matrix.catalog_version }}-spark${{ matrix.spark_version }}-java${{ matrix.java_version }}-scala${{ matrix.scala_version }}

      - name: Test Docker image
        run: |
          docker run --rm -d ${{ github.repository_owner }}/spark-connect:${{ matrix.catalog }}${{ matrix.catalog_version }}-spark${{ matrix.spark_version }}-java${{ matrix.java_version }}-scala${{ matrix.scala_version }} spark-submit --version
