name: Build Iceberg Spark Images

on:
  push:
    branches: [ main ]

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load matrix JSON
        id: set-matrix
        run: |
          MATRIX_JSON=$(jq -c . VERSIONS.json)
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  build:
    needs: load-matrix
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged

    strategy:
      matrix:
        include: ${{ fromJSON(needs.load-matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create image ENV variable
        run: |
          IMAGE=${{ github.repository_owner }}/spark-connect-server:${{ matrix.catalog }}${{ matrix.catalog_version }}-spark${{ matrix.spark_version }}-java${{ matrix.java_version }}-scala${{ matrix.scala_version }}
          echo "Building image: $IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build ./${{ matrix.catalog }} \
          --build-arg CATALOG_VERSION=${{ matrix.catalog_version }} \
          --build-arg JAVA_VERSION=${{ matrix.java_version }} \
          --build-arg SCALA_VERSION=${{ matrix.scala_version }} \
          --build-arg SPARK_VERSION=${{ matrix.spark_version }} \
          -t ${{ env.IMAGE }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Test Docker image
        run: |
          pip install -r tests/requirements.txt
          pip install pyspark==${{ matrix.spark_version }}
          pytest -vs tests/
